server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: http://localhost:8184/
          predicates:
            - Path=/clientes/**
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/products/**
        - id: service-operations
          uri: lb://service-operations
          predicates:
            - Path=/operations/**
        - id: service-manage
            uri: lb://service-manage
            predicates:
              - Path=/manages/**
